# Generated by Django 3.1.2 on 2020-10-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50)),
                ('amail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='book_info',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('publisher', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('no_of_copies', models.IntegerField()),
                ('available_copies', models.IntegerField()),
            ],
        ),
    ]
