# Generated by Django 3.1.2 on 2020-10-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201021_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=50)),
                ('amail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=10)),
                ('member_type', models.CharField(max_length=10)),
                ('joining_date', models.DateField()),
                ('no_of_issued_books', models.IntegerField()),
            ],
        ),
    ]
