# Generated by Django 3.1.2 on 2020-10-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='no_of_issued_books',
            field=models.IntegerField(default=0),
        ),
    ]
