# Generated by Django 3.1.2 on 2020-10-21 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20201021_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
