# Generated by Django 3.1.2 on 2020-10-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20201021_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book_info')),
            ],
        ),
        migrations.CreateModel(
            name='book_author',
            fields=[
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.book_info')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
            ],
        ),
        migrations.CreateModel(
            name='borrower',
            fields=[
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.books')),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField(default=None)),
                ('book_due', models.IntegerField(default=0)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.member')),
            ],
        ),
    ]
