# Generated by Django 3.1.2 on 2020-10-23 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_author_books_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_author',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author', unique=True),
        ),
        migrations.AlterField(
            model_name='book_author',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.book_info', unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book_info', unique=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.books', unique=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.member', unique=True),
        ),
    ]
