# Generated by Django 3.1.2 on 2020-10-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20201023_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_author',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.book_info'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.books'),
        ),
    ]
