# Generated by Django 3.1.2 on 2020-10-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20201023_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
