# Generated by Django 3.1.2 on 2020-11-01 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20201031_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
