# Generated by Django 3.1.2 on 2020-11-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20201101_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
