# Generated by Django 3.1.2 on 2020-11-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20201101_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
